### ISSUE TITLE
Intermittent test failures on dirty_stream_not_returned

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#165]
We just got a test failure on master:

```
---- test::agent_test::dirty_streams_not_returned stdout ----
thread 'test::agent_test::dirty_streams_not_returned' panicked at 'resp_to_be_dropped failed: BadStatus', src/test/agent_test.rs:214:9
```

Doesn't reproduce after a couple of tries locally. Not sure what the problem is. But we should probably consider this a blocker on releasing 1.5.0.

**Comment by jsha** [comment]
A little more detail from a failed run on #166:

```
---- test::agent_test::dirty_streams_not_returned stdout ----
thread 'test::agent_test::dirty_streams_not_returned' panicked at 'resp_to_be_dropped failed: Io(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })', src/test/agent_test.rs:214:9
```

**Comment by jsha** [comment]
I think I see the issue. The handler for testserver does one request/response and then returns, which drops the TcpStream, which closes it. That seems to result in a ConnectionReset error rather than the ConnectionAborted that we specifically handle as BadStatusRead. I suspect there's a race condition in terms of whether the connection is reset already by the time PoolReturnRead reads to the end (in which case the stream is not returned to the pool), or the connection is not yet reset by the time PoolReturnRead reads to the end (in which case the stream is returned to the pool, and later errors).

I think the best solution is to treat both ConnectionReset and ConnectionAborted as retryable. While I'm at it I'd like to implement the TODO in unit.rs and treat connection failures at any point as retryable, if the request and body are able to be retried.
