### ISSUE TITLE
Intermittent test error since #234 landed

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#237]
I'm getting this test error approximately 1 out of 2 test runs. I checked out the prior commit and ran the tests a bunch of time without reproducing, so it's probably something in #234. I'll investigate.

```
---- test::agent_test::dirty_streams_not_returned stdout ----
Error: Error { kind: Io, message: None, url: Some("http://localhost:45341/"), source: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }), response: None }
thread 'test::agent_test::dirty_streams_not_returned' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /home/jsha/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:193:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panicking.rs:483:5
   1: std::panicking::begin_panic_fmt
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panicking.rs:437:5
   2: test::assert_test_result
             at /home/jsha/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:193:5
   3: ureq::test::agent_test::dirty_streams_not_returned::{{closure}}
             at ./src/test/agent_test.rs:136:1
   4: core::ops::function::FnOnce::call_once
             at /home/jsha/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by jsha** [comment]
Fixed!
